import type { LucideIcon } from 'lucide-react';
import {
  ArrowRight,
  Building2,
  Circle,
  Calendar,
  CalendarClock,
  Contact,
  CreditCard,
  Diamond,
  Droplets,
  FileText,
  Hash,
  Heading1,
  IdCard,
  Image,
  Landmark,
  MapPin,
  Minus,
  MoveRight,
  PenLine,
  ScrollText,
  Shapes,
  Sigma,
  Square,
  Star,
  StickyNote,
  Table2,
  Text,
  Triangle,
  Type,
  User,
  UserRound,
} from 'lucide-react';
import { ComponentType } from '@invogen/shared';

/** Per-palette-id icons matching the reference sidebar artwork. */
const ICON_BY_KEY: Record<string, LucideIcon> = {
  media_image: Image,
  media_logo: Landmark,
  media_signature: PenLine,
  media_watermark: Droplets,
  basic_divider: Minus,
  basic_header: Heading1,
  basic_text: Text,
  basic_table: Table2,
  basic_invoice_table: Table2,
  basic_invoice_table_2: Table2,
  basic_invoice_table_3: Table2,
  shape_rectangle: Square,
  shape_rounded: Square,
  shape_circle: Circle,
  shape_triangle: Triangle,
  shape_diamond: Diamond,
  shape_star: Star,
  shape_line: Minus,
  shape_arrow: MoveRight,
  card_address: MapPin,
  card_company: Building2,
  card_customer: Contact,
  card_payment: CreditCard,
  field_gst: Hash,
  field_pan: IdCard,
  field_invoice: FileText,
  field_date: Calendar,
  field_due_date: CalendarClock,
  context_page_no: Sigma,
  context_note: StickyNote,
  context_footer: Type,
  context_term: ScrollText,
};

const TYPE_FALLBACK: Record<string, LucideIcon> = {
  [ComponentType.IMAGE]: Image,
  [ComponentType.LOGO]: Landmark,
  [ComponentType.SIGNATURE]: PenLine,
  [ComponentType.TEXT]: Text,
  [ComponentType.HEADING]: Heading1,
  [ComponentType.DIVIDER]: Minus,
  [ComponentType.COMPANY_CARD]: Building2,
  [ComponentType.CUSTOMER_CARD]: User,
  [ComponentType.ADDRESS]: MapPin,
  [ComponentType.INVOICE_NUMBER]: Hash,
  [ComponentType.DATE]: Calendar,
  [ComponentType.DUE_DATE]: CalendarClock,
  [ComponentType.GST_NUMBER]: Hash,
  [ComponentType.PAN_NUMBER]: IdCard,
  [ComponentType.PAYMENT_DETAILS]: CreditCard,
  [ComponentType.PRODUCT_TABLE]: Table2,
  [ComponentType.INVOICE_TABLE]: Table2,
  [ComponentType.INVOICE_TABLE_2]: Table2,
  [ComponentType.INVOICE_TABLE_3]: Table2,
  [ComponentType.TABLE]: Table2,
  [ComponentType.TERMS]: ScrollText,
  [ComponentType.NOTES]: StickyNote,
  [ComponentType.FOOTER]: Type,
  [ComponentType.WATERMARK]: Droplets,
  [ComponentType.PAGE_NUMBER]: Sigma,
  [ComponentType.RECTANGLE]: Square,
  [ComponentType.ROUNDED_RECT]: Square,
  [ComponentType.CIRCLE]: Circle,
  [ComponentType.TRIANGLE]: Triangle,
  [ComponentType.DIAMOND]: Diamond,
  [ComponentType.STAR]: Star,
  [ComponentType.LINE]: Minus,
  [ComponentType.ARROW]: ArrowRight,
};

export function getAssetIcon(type: string, iconKey?: string): LucideIcon {
  if (iconKey && ICON_BY_KEY[iconKey]) return ICON_BY_KEY[iconKey];
  return TYPE_FALLBACK[type] ?? Shapes;
}
