import type { LucideIcon } from 'lucide-react';
import {
  ArrowRight,
  AtSign,
  Building2,
  CalendarDays,
  Circle,
  Calendar,
  CalendarClock,
  Contact,
  CreditCard,
  Diamond,
  Droplets,
  FileText,
  Globe2,
  Hash,
  Heading1,
  IdCard,
  Image,
  Landmark,
  Mail,
  MapPin,
  MapPinned,
  Minus,
  MoveRight,
  PenLine,
  PhoneCall,
  QrCode,
  ScrollText,
  Shapes,
  ShieldCheck,
  Sigma,
  Smartphone,
  Square,
  Star,
  StickyNote,
  Table2,
  Text,
  Triangle,
  Type,
  User,
  UserRound,
  Wallet,
  WalletCards,
} from 'lucide-react';
import { ComponentType } from '@invogen/shared';

/** Per-palette-id icons matching the reference sidebar artwork. */
const ICON_BY_KEY: Record<string, LucideIcon> = {
  media_image: Image,
  media_logo: Landmark,
  media_signature: PenLine,
  media_watermark: Droplets,
  basic_divider: Minus,
  basic_header: Heading1,
  basic_text: Text,
  basic_table: Table2,
  basic_invoice_table: Table2,
  basic_invoice_table_2: Table2,
  basic_invoice_table_3: Table2,
  shape_rectangle: Square,
  shape_rounded: Square,
  shape_circle: Circle,
  shape_triangle: Triangle,
  shape_diamond: Diamond,
  shape_star: Star,
  shape_line: Minus,
  shape_arrow: MoveRight,
  card_address: MapPin,
  card_company: Building2,
  card_customer: Contact,
  card_payment: CreditCard,
  field_gst: Hash,
  field_pan: IdCard,
  field_invoice: FileText,
  field_date: Calendar,
  field_due_date: CalendarClock,
  field_company: Building2,
  field_customer: UserRound,
  field_payment: CreditCard,
  field_heading: Heading1,
  field_person: UserRound,
  field_address: MapPin,
  field_email: Mail,
  field_phone: PhoneCall,
  field_bank: Landmark,
  field_account: Wallet,
  field_ifsc: Landmark,
  field_upi: QrCode,
  field_generic: Text,
  library_phone: PhoneCall,
  library_mobile: Smartphone,
  library_email: Mail,
  library_at: AtSign,
  library_address: MapPinned,
  library_person: UserRound,
  library_building: Building2,
  library_bank: Landmark,
  library_card: CreditCard,
  library_wallet: WalletCards,
  library_gst: Hash,
  library_pan: IdCard,
  library_calendar: CalendarDays,
  library_globe: Globe2,
  library_upi: QrCode,
  library_verified: ShieldCheck,
  context_page_no: Sigma,
  context_note: StickyNote,
  context_footer: Type,
  context_term: ScrollText,
};

const TYPE_FALLBACK: Record<string, LucideIcon> = {
  [ComponentType.IMAGE]: Image,
  [ComponentType.LOGO]: Landmark,
  [ComponentType.SIGNATURE]: PenLine,
  [ComponentType.TEXT]: Text,
  [ComponentType.HEADING]: Heading1,
  [ComponentType.DIVIDER]: Minus,
  [ComponentType.COMPANY_CARD]: Building2,
  [ComponentType.CUSTOMER_CARD]: User,
  [ComponentType.ADDRESS]: MapPin,
  [ComponentType.INVOICE_NUMBER]: Hash,
  [ComponentType.DATE]: Calendar,
  [ComponentType.DUE_DATE]: CalendarClock,
  [ComponentType.GST_NUMBER]: Hash,
  [ComponentType.PAN_NUMBER]: IdCard,
  [ComponentType.FIELD]: Hash,
  [ComponentType.ICON]: Shapes,
  [ComponentType.PAYMENT_DETAILS]: CreditCard,
  [ComponentType.PRODUCT_TABLE]: Table2,
  [ComponentType.INVOICE_TABLE]: Table2,
  [ComponentType.INVOICE_TABLE_2]: Table2,
  [ComponentType.INVOICE_TABLE_3]: Table2,
  [ComponentType.TABLE]: Table2,
  [ComponentType.TERMS]: ScrollText,
  [ComponentType.NOTES]: StickyNote,
  [ComponentType.FOOTER]: Type,
  [ComponentType.WATERMARK]: Droplets,
  [ComponentType.PAGE_NUMBER]: Sigma,
  [ComponentType.RECTANGLE]: Square,
  [ComponentType.ROUNDED_RECT]: Square,
  [ComponentType.CIRCLE]: Circle,
  [ComponentType.TRIANGLE]: Triangle,
  [ComponentType.DIAMOND]: Diamond,
  [ComponentType.STAR]: Star,
  [ComponentType.LINE]: Minus,
  [ComponentType.ARROW]: ArrowRight,
};

export function getAssetIcon(type: string, iconKey?: string): LucideIcon {
  if (iconKey && ICON_BY_KEY[iconKey]) return ICON_BY_KEY[iconKey];
  return TYPE_FALLBACK[type] ?? Shapes;
}

/** Resolve icon for a stored field/card iconKey (canvas + palette). */
export function getIconByKey(iconKey: string | null | undefined): LucideIcon | null {
  if (!iconKey) return null;
  return ICON_BY_KEY[iconKey] ?? null;
}
